---
env: development
exclude:
  - ".about.yml"
  - ".cfignore"
  - ".codeclimate.yml"
  - ".gitignore"
  - ".gitmodules"
  - ".hound.yml"
  - 404.html
  - api-endpoints
  - bin
  - build
  - circle.yml
  - config_blog.rb
  - CONTRIBUTING.md
  - examples/
  - favicon.ico
  - feed*
  - Gemfile*
  - ISSUE_TEMPLATE.md
  - killport
  - LICENSE.md
  - node_modules
  - package.json
  - pages/our-work.html
  - PULL_REQUEST_TEMPLATE.md
  - README.md
  - robots.txt
  - search-index*
  - spec/
  - tests/
  - tests/schema/tags.yml
  - tmp/
  - vendor
  - _data/digital-identity.yml
  - _data/digital-wallet.yml
  - _data/general-glossary.yml
  - _data/techy-terms.yml
  - .circleci/make-yaml.py
  - .circleci/pull-sheet.sh
---
